# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 无时间限制签到

on:
  workflow_dispatch:
  #  push:
  #    branches: [ "master" ]
  #  pull_request:
  #    branches: [ "master" ]
  schedule:
    - cron: 23 18 * * *

permissions:
  contents: read

jobs:
  signTask:
    name: '签到'
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action/base-environment
      - uses: ./.github/action/cache-data
      - name: 启动签到
        env:
          MULTI: ${{ vars.MULTI }}
          PUSH: ${{ secrets.PUSH  }}
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
        run: |
          python3 quark.py